[versions]
activityCompose = "1.9.0"
biometricKtx = "1.2.0-alpha05"
coil = "3.0.0-alpha06"
coreSplashscreen = "1.0.1"
espressoCore = "3.5.1"

koin = "3.5.6"
koin-ksp = "1.3.1"
koin-compose = "1.1.5"

kotlinxSerializationJson = "1.6.1"
kotlin-datetime = "0.6.0"
junitJupiter = "5.10.2"
mockitoCore = "5.7.0"
mockitoKotlin = "5.2.1"
junitVersion = "1.1.5"
junit = "4.13.2"
mockative = "2.0.1"

kotlinxCoroutinesCore = "1.8.0"
ktx = "1.13.1"
lifecycleRuntimeKtx = "2.7.0"
materialIconsExtended = "1.6.8"
navigationCompose = "2.7.7"
roomRuntime = "2.6.1"
bom = "2024.06.00"

decompose = "3.1.0"

#buld-compilers
compose-compiler = "1.6.10"
minSdk = "26"
compileSdk = "34"

andoid-gradle = "8.3.0"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.22"
appcompat = "1.7.0"
navigationRuntimeKtx = "2.7.7"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometricKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockative = { module = "io.mockative:mockative", version.ref = "mockative" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-material3 = { module = "androidx.compose.material3:material3" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-kmp = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }

junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
compose-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose-android = { module = "io.insert-koin:koin-androidx-compose" }
koin-compose-kmp = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }
koin-anotation = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

[bundles]
compose = ["compose-ui",
    "compose-ui-graphics",
    "compose-ui-preview",
    "compose-ui-material3"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "andoid-gradle" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "andoid-gradle" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialzation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-compiler" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
